[project]
name = "dl-util"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.3",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
    "yt-dlp>=2025.12.8",
]
